development:
  server: "http://localhost:9292/faye"
  secret_token: "secret_hai"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "e6599406101577d0c590a0d26c6e1caab7648a53a0e2c284216861c354de744d"
  signature_expiration: 3600 # one hour
